# Generated by Django 5.2.4 on 2025-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("guest_count", models.IntegerField()),
                ("reservation_time", models.DateTimeField()),
                ("comments", models.CharField(max_length=1000)),
            ],
        ),
    ]
