# Generated by Django 5.2.4 on 2025-07-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0002_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="reservation_time",
        ),
    ]
